### ISSUE TITLE
Add proxy-wide max-timeout to docker compose stack for nginx

### ISSUE THREAD

**Issue by surchs** [neurobagel/internal_deployment#1]
We want to have longer request timeouts for all proxied routes: https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#proxy-wide

This likely means editing the docker compose file for nginx: https://github.com/neurobagel/internal_deployment/blob/1f3bdbf521c0cbeb4590ea9f5d21c3d64020bbad/docker_nginx.yml#L10-L15

- [x] Look at docs for how to add global config settings to the current setup
- [x] add the proxy-wide timeout setting (increase to what it was on old Fairmount)
- [x] confirm NGINX still runs / restarts 
- [x] document anything important found on hackMD

**Comment by alyssadai** [comment]
@surchs, timeout seems to have been extended successfully. I tried one empty query and one 40+ age query in the query tool, and ON responded for both. Maybe you can try a few to confirm.

I linked the relevant section of the `nginx-proxy` docs along with an example for setting timeout in the HackMD docs. On `fairmount` the nginx configs can be found under `~/internal_deployment/nginx/`

**Comment by surchs** [comment]
Thank you very much for documenting this clearly @alyssadai! That's super cool! 

However I still get OpenNeuro timeout errors roughly half of the time when using the query tool:

```
{"errors":[{"node_name":"OpenNeuro","error":"Request failed due to a timeout: "}]
```

**Comment by rmanaem** [comment]
@surchs 
I think that issue is stemming from the `30s` timeout set on the federation API.
Addressing it here: https://github.com/neurobagel/federation-api/issues/93

**Comment by surchs** [comment]
I think we can close this issue as well now
